version: '3'

services:
  mongo:
    image: mongo
  app:
    build: .
    command: npm start
    environment:
      - NODE_ENV=development
      - MONGO_CONNECTION_URL=mongodb://mongo/app
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - mongo